import bannerImg from '../assets/images/mission.jpg'

export const blogData = [
    {
        id: 1, 
        title: 'How to Setup Coding Environment',
        desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Libero quos tenetur consectetur. Cupiditate facere magni ipsa accusamus illo voluptatem hic.',
        banner: bannerImg,
        category: 'Software Engineering',
        datePosted: 'May 16, 2025',
        views: 300
    },
      {
        id: 2,
        title: 'How to Setup Coding Environment',
        desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Libero quos tenetur consectetur. Cupiditate facere magni ipsa accusamus illo voluptatem hic.',
        banner: bannerImg,
        category: 'Software Engineering',
        datePosted: 'May 16, 2025',
        views: 300,
    },
      {
        id: 3,
        title: 'How to Setup Coding Environment',
        desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Libero quos tenetur consectetur. Cupiditate facere magni ipsa accusamus illo voluptatem hic.',
        banner: bannerImg,
        category: 'Software Engineering',
        datePosted: 'May 16, 2025',
        views: 300,
    },
      {
        id: 4,
        title: 'How to Setup Coding Environment',
        desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Libero quos tenetur consectetur. Cupiditate facere magni ipsa accusamus illo voluptatem hic.',
        banner: bannerImg,
        category: 'Software Engineering',
        datePosted: 'May 16, 2025',
        views: 300,
    },
     {
        id: 5,
        title: 'How to Setup Coding Environment',
        desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Libero quos tenetur consectetur. Cupiditate facere magni ipsa accusamus illo voluptatem hic.',
        banner: bannerImg,
        category: 'Software Engineering',
        datePosted: 'May 16, 2025',
        views: 300,
    },
     {
        id: 6,
        title: 'How to Setup Coding Environment',
        desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Libero quos tenetur consectetur. Cupiditate facere magni ipsa accusamus illo voluptatem hic.',
        banner: bannerImg,
        category: 'Software Engineering',
        datePosted: 'May 16, 2025',
        views: 300,
    },
     {
        id: 7,
        title: 'How to Setup Coding Environment',
        desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Libero quos tenetur consectetur. Cupiditate facere magni ipsa accusamus illo voluptatem hic.',
        banner: bannerImg,
        category: 'Software Engineering',
        datePosted: 'May 16, 2025',
        views: 300,
    },
     {
        id: 8,
        title: 'How to Setup Coding Environment',
        desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Libero quos tenetur consectetur. Cupiditate facere magni ipsa accusamus illo voluptatem hic.',
        banner: bannerImg,
        category: 'Software Engineering',
        datePosted: 'May 16, 2025',
        views: 300,
    }
]